#!/bin/sh

echo `date` $* >>/var/log/vacuumvpn-tls-verify.log

if [ "$1" -gt 0 ] ; then
  # Return ok if depth > 0
  exit 0
fi

for i in \
 'C=UK, O=eScience, OU=Manchester, L=HEP, CN=gridpp-vm.blackett.manchester.ac.uk'
do
  if [ "$2" == "$i" ] ; then
    # Found a matching DN, return ok
    exit 0
  fi
done

# No whitelisted DNs, so return not ok
exit 1
